-- Migration 004: incidents table
-- Matches docs/04-architecture/00-overview.md §6.3.1 "Incidents Schema" field-for-field.
-- Serves `GET /incidents?symbol=&from=&to=` (dynamic, time-ranged incidents only; the
-- separate static `/known-limitations` list, e.g. Binance forceOrder partial coverage,
-- is out of scope for this table -- per docs it's a static config/JSON, not a DB table).

CREATE DATABASE IF NOT EXISTS market_data;

CREATE TABLE IF NOT EXISTS market_data.incidents
(
    id               String,                            -- unique incident id (e.g. UUID, generated by the normalizer)

    exchange         LowCardinality(String),             -- open enum: 'binance', 'bybit', ...

    -- type: 'collector_disconnect' | 'orderbook_sequence_break' | 'reference_price_freeze'
    --       | 'backfill_gap' | 'clock_drift'  (see §6.3.1 table; open enum for future types)
    type             LowCardinality(String),

    severity         LowCardinality(String),             -- 'info' | 'warning' | 'critical'

    -- exchange-native vocabulary, NOT unified across exchanges (Binance: spot/usdtm/coinm;
    -- Bybit: spot/linear/inverse) -- interpreted together with `exchange`, per docs.
    segment          LowCardinality(String),

    symbol           Nullable(String),                   -- null if the incident affects the whole segment

    -- normalized, exchange-agnostic logical channel name:
    -- 'orderbook' | 'trades' | 'mark_price' | 'funding' | 'liquidations' | 'collector'
    -- literal exchange-native channel name (e.g. Binance 'depth'/'aggTrade') is preserved
    -- in details.source_channel, per docs -- not duplicated as its own column here.
    affected_channel LowCardinality(String),

    start_ts         DateTime64(3, 'UTC') CODEC(Delta, ZSTD),
    end_ts           Nullable(DateTime64(3, 'UTC')),      -- null while still open

    status           LowCardinality(String),              -- 'open' | 'resolved'

    description      String,                              -- human-readable summary

    detected_by      String,                               -- detector/rule name or system id

    -- type- and exchange-specific payload; always includes `source_channel`.
    -- Stored as a JSON-text String: ClickHouse's native JSON type is experimental
    -- and disabled by default (would require `allow_experimental_json_type=1`)
    -- on the pinned 24.8 server, so the application layer (normalizer) serializes/
    -- deserializes this as JSON text instead. Query with `JSONExtractString(details, 'source_channel')`
    -- or similar, or use ClickHouse's `simpleJSON*`/`JSONExtract*` functions.
    details          String,

    ingested_at      DateTime64(3, 'UTC') DEFAULT now64(3) CODEC(Delta, ZSTD)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(start_ts)
ORDER BY (exchange, start_ts, id)
SETTINGS index_granularity = 8192;
